name: Deploy to GCE VM

on:
  push:
    branches:
      - master # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H 35.184.225.142 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/github-actions-key rizwa@35.184.225.142 << 'EOF'
            cd ~/week-9
            git pull origin master
            npm install
            npm run build
            pm2 restart all
          EOF
